import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { AuthContextProvider } from "../contexts/AuthContext";
import { SliderContextProvider } from "../contexts/sliderContext";
import Footer from "../components/footer/Footer";
import { CartContextProvider } from "../contexts/CartContext";
import BreadCrumb from "../components/breadCrumb/BreadCrumb";
import { Suspense } from "react";
import { Roboto } from "next/font/google";
import MobileMenuComponent from "@/components/mobileMenuComponent/MobileMenuComponent";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthContextProvider>
          <CartContextProvider>
            <SliderContextProvider>
              <Navbar />
              <BreadCrumb />
              <div className="min-h-screen">
                <Suspense fallback={<AdvancedLoading />}>{children}</Suspense>
              </div>
              <MobileMenuComponent />
              <Footer />
            </SliderContextProvider>
          </CartContextProvider>
        </AuthContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}

function AdvancedLoading() {
  return (
    <div className="flex items-center justify-center h-screen bg-gray-100">
      <div className="relative flex items-center justify-center">
        {/* دایره های چرخشی */}
        <div className="absolute animate-spin-slow rounded-full border-4 border-t-transparent border-blue-500 w-24 h-24"></div>
        <div className="absolute animate-spin-fast rounded-full border-4 border-t-transparent border-purple-500 w-16 h-16"></div>
        {/* متن لودینگ */}
        <span className="absolute text-lg font-semibold text-gray-700">
          در حال بارگذاری...
        </span>
      </div>
    </div>
  );
}
